### ISSUE TITLE
Are we keeping this?

### ISSUE THREAD

**Issue by TimohStudios** [anchorcms/anchor-themes#13]
I'm wondering if we should keep this.  
We've got the wonderful anchorthemes.com, so I feel like we don't really need this repo.  
There's also the fact that nothing has been done here for a year now, so everything is outdated.  
  
I'm not saying we should remove this immediately (although I'd be fine with that), but maybe a **huge** deprecated warning in the readme with a link to Anchor Themes in there (because it's already in the readme, but way to far down, imo).  
  
Let me know what you think.

**Comment by guitmz** [comment]
is this going to be updated with the new anchor version? i've fixed the twitter integration, I could post a fix

**Comment by daviddarnes** [comment]
@guitmz thanks but this repo needs to be sorted out as we shouldn't be putting all these themes into one repo. At some point I'd like to split them into their own repo but still on the anchor-cms org. Then you could submit a pull request to that specific theme or themes.

**Comment by guitmz** [comment]
@daviddarnes sounds good to me :)

**Comment by daviddarnes** [comment]
New proposed plan of action that will solve this issue https://github.com/anchorcms/anchor-themes/issues/14
