### ISSUE TITLE
Theme Author Reclaim Plan

### ISSUE THREAD

**Issue by daviddarnes** [anchorcms/anchor-themes#14]
## Issue

This repo has existed for quite a while now. It holds the original themes that were created at the very of Anchor CMS. However, we have a couple issues with this repo.
1. Managing 8 themes in 1 repo is a bad way of working. Pull requests, branching and issue creating looks really confusing. Especially if it's to do with just 1 theme
2. If you want to download or fork a theme for your own use you take the other 7 with you. This also occurs on the Anchor Themes site as it directly links to the GitHub download zip
3. Author credit! This probably the most important thing in my eyes. At the minute nobody is taking credit for the themes and I'd like to change that
## Proposed Solution

Here is what I plan to do with this repo:
- [x] Duplicate the repo 7 times over onto my own account (this excludes Default theme as it is currently being worked on within [anchor-cms](https://github.com/anchorcms/anchor-cms)). Yes this does look like I'm trying to take credit for these themes, but I'm definitely not. I'll be making sure the README.md has an explanation to why it's on my account
- [x] Rename each duplicated repo to the name of each theme
- [x] Clean out the other repos so that there are 7 repos with a single theme in it
- [x] Clear out the themes from [this repo](https://github.com/anchorcms/anchor-themes) and update the README.md stating what has happened and where the themes have gone
- [x] Contact all the theme authors as best as I can and explain the situation and provide a simple method to change ownership of the repo over

Thoughts? This shouldn't take long to do and will hopefully make it easier for authors to claim back their theme, if not at least it means that we can manage the themes easier.

**Comment by guitmz** [comment]
I find the solution reasonable, good idea!

**Comment by daviddarnes** [comment]
## Update

I've taken a brief look into each theme and dug out each of the authors. They are as follows:

- Awetheme by @CosminNegoita (seems to be called 'TutTheme' in some places)
- Dark-bar by @CraigChilds94 & @idiot (adapted from the original Default theme)
- Elcapor by @CraigChilds94
- Greaves by Russell Jones
- Plain by Chris Veto
- Prototype by @CosminNegoita
- Sando by @CosminNegoita

Sadly I couldn't get the right GitHub accounts for Russell Jones and Chris Veto. 

**For the rest of you could you please read the issue at the top of this page. If you do not reply I assume you are happy for me to proceed with the intended plan. Each theme that isn't taken back up by their original author will be moved to my account but will continue to credit the original author. If you change your mind after the move I will be more than happy to change the repo ownership over**

**Comment by daviddarnes** [comment]
## Update 2

I've copied all the themes over to my account, cleared them out so they only contain the relevant theme and made sure to mention the author in the description:
- https://github.com/daviddarnes/awetheme
- https://github.com/CraigChilds94/dark-bar
- https://github.com/CraigChilds94/elcapor
- https://github.com/daviddarnes/greaves
- https://github.com/daviddarnes/plain
- https://github.com/daviddarnes/prototype
- https://github.com/daviddarnes/sando

**Next:**
- [x] Update the README.md files on this repo to indicate where the themes have moved to
- [x] Remove the themes from this repo to stop people using outdated themes
- [x] Update each README.md in each theme repo to reflect that particular theme

**Comment by daviddarnes** [comment]
And we're all done! This repo is as follows: https://github.com/anchorcms/anchor-themes/blob/master/readme.md

…and the new repos are as follows:
- Awetheme: **https://github.com/daviddarnes/awetheme**
- Dark-bar: **https://github.com/CraigChilds94/dark-bar**
- Elcapor: **https://github.com/CraigChilds94/elcapor**
- Greaves: **https://github.com/daviddarnes/greaves**
- Plain: **https://github.com/daviddarnes/plain**
- Prototype: **https://github.com/daviddarnes/prototype**
- Sando: **https://github.com/daviddarnes/sando**
- Default: **https://github.com/anchorcms/anchor-cms/tree/master/themes/default**

Hopefully people won't get confused by the change, I think due to the age of these themes they aren't looked at very often.
